### ISSUE TITLE
Delete a Facility Concern

### ISSUE THREAD

**Issue by steesdale** [MichaelKambenga/ihfr_curation#62]
As a system admin, 

I want to make sure that a user only deletes a facility at the appropriate times.  

For instance a facility that moves or is closed, should not be deleted.  A facility that is a duplicate could need to be deleted. 

To resolve this, review the process and help guide a user with the UI to remove duplicates but not delete closing or when moving facilities out of their admin zone. 

Reported by Ilomo

**Comment by niamhdarcy** [comment]
The users have now been advised.  The facilities that were marked as delete that are really closed were rejected, and then re-entered with a request for closure.
