### ISSUE TITLE
Pending Request - UI Enhancement Request

### ISSUE THREAD

**Issue by steesdale** [MichaelKambenga/ihfr_curation#63]
Ilomo and MOH requested the following enhancement to the UI ... Follow up with the MOH for additional detail if needed.

When sitting at the main landing page... the number of pending requests is presented as the number in the top right.  A user experience feedback bit from the MOH was that this number should actual sit with the "Pending Requests" button, not the user profile icon.

![screen shot 2014-07-21 at 8 42 43 pm](https://cloud.githubusercontent.com/assets/3987608/3647498/5d358d3a-10ff-11e4-8ecd-6004da9bfbb4.png)

**Comment by niamhdarcy** [comment]
This is now closed.  The pending requests is now on the main requests page
