### ISSUE TITLE
Curation tool saves record w/o admin hierarhcy

### ISSUE THREAD

**Issue by steesdale** [MichaelKambenga/ihfr_curation#67]
There have been reports of the curation tool not submitting the approved records/updates for a facility to the official collection.  Should be triaged to isolate where the issue is coming from.

**Comment by gmcressman** [comment]
Are there two issues here? 1. Curation tool permits user to add record without requiring any values in admin hierarchy, and 2. Records approved in curation tool do not appear in official collection in Resource Map?

**Comment by MichaelKambenga** [comment]
We are working on the reported issue of the changes being approved in the curation tool but are not reflected in the official collection.We are using the Health Facility reported by @Nseya to reproduce this.

**Comment by MichaelKambenga** [comment]
Fixed now,the curation tool now does not allow user to add a record without admin hierarchy.
