### ISSUE TITLE
Search, Facility Details => PHP Error

### ISSUE THREAD

**Issue by gmcressman** [MichaelKambenga/ihfr_curation#68]
1) Logged in as gmc@rti.org
2) Search
3) Facility Details

![image](https://cloud.githubusercontent.com/assets/329768/8647055/5a439370-295d-11e5-8070-68cb7a4e81bb.png)

**Comment by MichaelKambenga** [comment]
@gmcressman 
Sorry the error occurred because no searching criteria was supplied,there was no checking for it,
Fixed now,
Thanks...
