### ISSUE TITLE
DHIS Integration test 1.2.1.g - Facility type did not change in dhis SQL view

### ISSUE THREAD

**Issue by niamhdarcy** [MichaelKambenga/ihfr_curation#69]
Using V0.1 test plan for the HFR-DHIS2 integration testing, this test failed.  Update several facilities (now identify these as test facilities) in the Curation Tool and validate the changes show in DHIS2 for Facility Type.  Sub-test g validates that all of these changes show in the SQL VIEW.  This includes several changes to facility_type.

**Comment by Nseya** [comment]
This issue is now closed as facility type changes in SQL view,
