### ISSUE TITLE
DHIS-HFR integration test 1.3.1.c - Facility was deleted in DHIS without sending email to UDSM

### ISSUE THREAD

**Issue by niamhdarcy** [MichaelKambenga/ihfr_curation#72]
The facility was deleted in DHIS when approved for deletion in the cureation tool.  No email was sent to UDSM to inform them.

**Comment by Nseya** [comment]
Notification email is sent when a facility is deleted in HFR
![deleted facility test](https://cloud.githubusercontent.com/assets/12272999/11650595/7dd4ed90-9d9b-11e5-8e08-d830039d0e17.PNG)
