### ISSUE TITLE
Need to include Registration Status in email when HF changes to Operatoinal; Also when operational HF goes from Not Reg to REG need to send email

### ISSUE THREAD

**Issue by niamhdarcy** [MichaelKambenga/ihfr_curation#76]
It seems that for private facilities, they can be operational but not registered yet, which means they are not supposed to report on MTUHA.  we need to include the registratoin status in the email that is sent to UDSM notifying UDSM that the HF has changed to operational.  So send operational and regsitratoin status.  As already send the information about ownership type, then UDSM can check the registration status if the HF is private, and if Not Registered, then do not need to create the facility.

Also, if a facility changes from Not Registered to Registered, and is operational and private, then an email also needs to go to UDSM as this HF will now need to be added into DHIS2 and UDSM can check with the HF which services they offer to enable reports.

**Comment by Nseya** [comment]
Email notification is sent when a facility changes its registration status

![reg status changes](https://cloud.githubusercontent.com/assets/12272999/12839591/03e124fc-cbec-11e5-982c-25820729131d.JPG)
